[project]
name = "sakila-lab-alessandro-abbate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,sql-database]>=1.18.2",
    "ipykernel>=7.1.0",
]
